pipeline {
    agent any
    stages {
        stage('one') {
            steps {
                echo 'Hello World'
            }
        }
	stage('two') {
	    steps {
	        echo 'Acorp'
            }
	}
	stage('three') {
	    steps {
	        echo 'Pcorp'
	    }
	}
     }
}
